### ISSUE TITLE
Multi-class option

### ISSUE THREAD

**Issue by meldogs** [SvenWerlen/fvtt-spellcaster-utility-pf1#1]
Can this be made to check for a secondary casting class and add it to the Prepare and Cast Spells screens?

**Comment by SvenWerlen** [comment]
Although it's not very user-friendly, you can create another macro and change the settings to support "secondary", "tertiary", ... spellbooks. Simply replace "primary" with "secondary" and it should work. Let me know if it's not the case.

![image](https://user-images.githubusercontent.com/938060/93408141-d195e800-f861-11ea-9e73-ba06f870a74b.png)

**Comment by meldogs** [comment]
I tried that and yes it works. Is there a way to change the macro so that it puts both the primary and secondary on the same screen?

**Comment by SvenWerlen** [comment]
No, it's not yet possible. But if you like, I can extend it with a list like this: `spellbooks: ['primary','secondary']`.
Let me know. 
Btw, I hope that you like the module so far.

**Comment by meldogs** [comment]
That would be awesome and super useful. Thank you for creating and supporting this module. It is really handy.

**Comment by SvenWerlen** [comment]
Noted. I'll work on this. It's not that simple because the logic behind each spellbook might be different depending on the type (ex: spontaneous) and the total number of spells differs for each level. Do you want to have it clearly separated or mixed together?

**Comment by meldogs** [comment]
Separated would be good I think. I have a Cleric / Wizard multi-class in my current game and it would be good for him to see the division between the two. I didn't know that this was usable with spontaneous casters. Is it something my bard could use too? Thanks again for your time on this. I appreciate it.

**Comment by SvenWerlen** [comment]
I finally decided not to implement this because of the complexity to handle potentially different type of magic and merge information on the scree. However, if some contributor provides a pull request for this implementation, I will review it and accept it. Thanks for your understanding.
