### ISSUE TITLE
Not V10 compatible

### ISSUE THREAD

**Issue by Co0nmz** [SvenWerlen/fvtt-spellcaster-utility-pf1#6]
The module does not work in V10 :(

**Comment by SvenWerlen** [comment]
Version `v-2.0.0` now supports V10. Thank you for reporting it (and using this module)

**Comment by Co0nmz** [comment]
Quickest fix in history :D thanks a lot!

**Comment by SvenWerlen** [comment]
Thanks!
It took me 7 months to work on the other one (open/close window). 
I didn't remember it :-)
